# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Bun updates
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates daily
    groups:
      bun:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Check for updates daily
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
