# Configuration for GitHub PR Labeler
# https://github.com/actions/labeler

arkenv:
  - changed-files:
    - any-glob-to-any-file: 'packages/arkenv/**/*'

vite-plugin:
  - changed-files:
    - any-glob-to-any-file: 'packages/vite-plugin/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: 'apps/docs/**/*'

examples:
  - changed-files:
    - any-glob-to-any-file: 'examples/**/*'