name: dynamic-labeler
description: "Dynamically label pull requests based on changed files using paths-filter"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      arkenv: ${{ steps.changes.outputs.arkenv }}
      vite-plugin: ${{ steps.changes.outputs.vite-plugin }}
      docs: ${{ steps.changes.outputs.docs }}
      examples: ${{ steps.changes.outputs.examples }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            arkenv:
              - 'packages/arkenv/**'
            vite-plugin:
              - 'packages/vite-plugin/**'
            docs:
              - 'apps/docs/**'
            examples:
              - 'examples/**'

  apply-labels:
    runs-on: ubuntu-latest
    needs: detect-changes
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Add arkenv label
        if: needs.detect-changes.outputs.arkenv == 'true'
        run: gh pr edit "$PR_NUMBER" --add-label "arkenv" --repo ${{ github.repository }}

      - name: Add @arkenv/vite-plugin label
        if: needs.detect-changes.outputs.vite-plugin == 'true'
        run: gh pr edit "$PR_NUMBER" --add-label "@arkenv/vite-plugin" --repo ${{ github.repository }}

      - name: Add docs label
        if: needs.detect-changes.outputs.docs == 'true'
        run: gh pr edit "$PR_NUMBER" --add-label "docs" --repo ${{ github.repository }}

      - name: Add example label
        if: needs.detect-changes.outputs.examples == 'true'
        run: gh pr edit "$PR_NUMBER" --add-label "example" --repo ${{ github.repository }}

      - name: Remove arkenv label
        if: needs.detect-changes.outputs.arkenv == 'false'
        run: gh pr edit "$PR_NUMBER" --remove-label "arkenv" --repo ${{ github.repository }} || true

      - name: Remove @arkenv/vite-plugin label
        if: needs.detect-changes.outputs.vite-plugin == 'false'
        run: gh pr edit "$PR_NUMBER" --remove-label "@arkenv/vite-plugin" --repo ${{ github.repository }} || true

      - name: Remove docs label
        if: needs.detect-changes.outputs.docs == 'false'
        run: gh pr edit "$PR_NUMBER" --remove-label "docs" --repo ${{ github.repository }} || true

      - name: Remove example label
        if: needs.detect-changes.outputs.examples == 'false'
        run: gh pr edit "$PR_NUMBER" --remove-label "example" --repo ${{ github.repository }} || true